#Requires -Version 5.1
<#
.SYNOPSIS
    Builds the HiveMotion installer with the .NET 8 Desktop Runtime bootstrapper.
.DESCRIPTION
    1. Publishes the framework-dependent app output.
    2. Generates HarvestedFiles.wxs from the publish directory.
    3. Builds the WiX MSI for the app.
    4. Builds the WiX bundle that installs the .NET 8 Desktop Runtime when missing.
    5. Copies the final setup executable to Installer/artifacts/.

    Run this script from the repository root on a Windows machine that has the
    .NET SDK and WiX Toolset installed.
#>
[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',

    [string]$ArtifactsDir = "$PSScriptRoot\artifacts"
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$publishProfile = 'FrameworkDependent'
$publishDir = "$root\Installer\publish"
$setupDir = "$root\Installer\HiveMotion.Setup"
$harvestedWxs = "$setupDir\HarvestedFiles.wxs"

Write-Host "Publishing HiveMotion (framework-dependent)..." -ForegroundColor Cyan
dotnet publish "$root\HiveMotion\HiveMotion.csproj" `
    -p:PublishProfile=$publishProfile `
    -c $Configuration

if (-not (Test-Path $publishDir)) {
    throw "Publish directory not found: $publishDir"
}

Write-Host "Harvesting published files into $harvestedWxs ..." -ForegroundColor Cyan

$files = Get-ChildItem -Path $publishDir -File -Recurse
if ($files.Count -eq 0) {
    throw "No files found in publish directory: $publishDir"
}

$xml = [System.Xml.XmlWriter]::Create($harvestedWxs, [System.Xml.XmlWriterSettings]@{
    Indent = $true
    IndentChars = "  "
    Encoding = [System.Text.UTF8Encoding]::new($false)
})

try {
    $xml.WriteStartDocument()
    $xml.WriteComment(" This file is generated by Installer\build-installer.ps1. Do not edit manually. ")
    $xml.WriteStartElement('Wix', 'http://wixtoolset.org/schemas/v4/wxs')
    $xml.WriteStartElement('Fragment')
    $xml.WriteStartElement('ComponentGroup')
    $xml.WriteAttributeString('Id', 'HarvestedAppComponents')
    $xml.WriteAttributeString('Directory', 'INSTALLFOLDER')

    $fileIndex = 0
    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($publishDir.Length).TrimStart('\')
        $subdirectory = [System.IO.Path]::GetDirectoryName($relativePath)

        $xml.WriteStartElement('Component')
        if (-not [string]::IsNullOrEmpty($subdirectory)) {
            $xml.WriteAttributeString('Subdirectory', $subdirectory)
        }

        $xml.WriteStartElement('File')
        $xml.WriteAttributeString('Source', $file.FullName)
        $xml.WriteEndElement() # File

        $xml.WriteEndElement() # Component
        $fileIndex++
    }

    $xml.WriteEndElement() # ComponentGroup
    $xml.WriteEndElement() # Fragment
    $xml.WriteEndElement() # Wix
    $xml.WriteEndDocument()
}
finally {
    $xml.Dispose()
}

Write-Host "Harvested $fileIndex file(s)." -ForegroundColor Green

Write-Host "Building WiX installer projects..." -ForegroundColor Cyan
dotnet build "$root\HiveMotion.Installer.sln" `
    -c $Configuration `
    -p:Platform=x64

Write-Host "Copying installer artifacts..." -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $ArtifactsDir | Out-Null

$bootstrapperOutput = "$root\Installer\HiveMotion.Bootstrapper\bin\x64\$Configuration\HiveMotion.Bootstrapper.exe"
$msiOutput = "$root\Installer\HiveMotion.Setup\bin\x64\$Configuration\HiveMotion.Setup.msi"

if (Test-Path $bootstrapperOutput) {
    Copy-Item $bootstrapperOutput "$ArtifactsDir\HiveMotion-Setup.exe" -Force
    Write-Host "Bootstrapper: $ArtifactsDir\HiveMotion-Setup.exe" -ForegroundColor Green
}
else {
    Write-Warning "Bootstrapper output not found at $bootstrapperOutput"
}

if (Test-Path $msiOutput) {
    Copy-Item $msiOutput "$ArtifactsDir\HiveMotion-Setup.msi" -Force
    Write-Host "MSI: $ArtifactsDir\HiveMotion-Setup.msi" -ForegroundColor Green
}
else {
    Write-Warning "MSI output not found at $msiOutput"
}

Write-Host "Done." -ForegroundColor Cyan
